version: '3.8'
networks:
  backend:
    driver: bridge
services:
  backend:
    build: .
    image: backend:latest
    environment:
      API_PORT: ${API_PORT}
      API_KEY: ${API_KEY}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_PWD: ${DB_PWD}
      DB_USER: ${DB_USER}
      NODE_ENV: development
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend      
  db:
    image: postgres:alpine3.17
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend